# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('apellidos', models.CharField(db_column='APELLIDOS', max_length=100)),
            ],
            options={
                'db_table': 'vendedores',
                'managed': True,
            },
        ),
    ]
