# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendedores',
            new_name='Trabajadores',
        ),
        migrations.AlterModelOptions(
            name='trabajadores',
            options={'managed': True, 'verbose_name_plural': 'Trabajadores'},
        ),
    ]
